query GetParents($searchTerm: String) {
  parents(searchTerm: $searchTerm) {
    id
    name
    surname
  }
}

mutation CreateParent($input: ParentInput!) {
  createParent(input: $input) {
    __typename

    ... on MutationCreateParentSuccess {
      data {
        id
      }
    }

    ... on AppError {
      __typename
      message
    }

    ... on UniqueConstraintError {
      __typename
      message
    }
  }
}

mutation UpdateParent($input: ParentInput!) {
  updateParent(input: $input) {
    __typename

    ... on MutationUpdateParentSuccess {
      data {
        id
      }
    }

    ... on AppError {
      __typename
      message
    }

    ... on UniqueConstraintError {
      __typename
      message
    }

    # ... on NotFoundError {
    #   __typename
    #   message
    # }
  }
}
