query GetInvoices($filter: InvoiceFilter) {
  invoices(filter: $filter) {
    id
    number
    title
    amount
    grades {
      id
    }
  }
}

mutation CreateInvoice($input: InvoiceInput!) {
  createInvoice(input: $input) {
    __typename

    ... on MutationCreateInvoiceSuccess {
      data {
        id
      }
    }

    ... on AppError {
      __typename
      message
    }
  }
}

mutation UpdateInvoice($input: InvoiceInput!) {
  updateInvoice(input: $input) {
    __typename

    ... on MutationUpdateInvoiceSuccess {
      data {
        id
      }
    }

    ... on AppError {
      __typename
      message
    }

    ... on NotFoundError {
      __typename
      message
    }
  }
}

mutation InitializeFeePayment($input: FeePaymentInput!) {
  initiateFeePayment(input: $input) {
    __typename

    ... on MutationInitiateFeePaymentSuccess {
      data {
        authorization_url
        access_code
        reference
      }
    }

    ... on AppError {
      __typename
      message
    }
  }
}

mutation VerifyPaymentStatus($reference: String!) {
  verifyPaymentStatus(reference: $reference) {
    __typename

    ... on MutationVerifyPaymentStatusSuccess {
      data {
        id
        reference
        amountPaid
        payerEmail
        paidAt
        students {
          id
          name
          surname
        }
      }
    }

    ... on AppError {
      __typename
      message
    }
  }
}
